Controllers/DrinkController.cs
using DrinkAndGo.Data.Interfaces;
using DrinkAndGo.Data.Models;
using DrinkAndGo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace DrinkAndGo.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DrinkController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;
        private readonly IDrinkRepository _drinkRepository;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DrinkController(ICategoryRepository categoryRepository, IDrinkRepository drinkRepository, IWebHostEnvironment webHostEnvironment )
        {
            _categoryRepository = categoryRepository;
            _drinkRepository = drinkRepository;
            this.webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        [AllowAnonymous]
        public IActionResult List(string category)
        {

            IEnumerable<Drink> drinks;
            string currentCategory = string.Empty;
            if (string.IsNullOrEmpty(category))
            {
                drinks = _drinkRepository.Drinks.OrderBy(d => d.DrinkId);
                currentCategory = "All Drink";
            }
            else
            {
                if (string.Equals("Alcoholic", category, StringComparison.OrdinalIgnoreCase))
                {
                    drinks = _drinkRepository.Drinks
                        .Where(p => p.Category.CategoryName == "Alcoholic").OrderBy(p => p.Name);
                }
                else
                {
                    drinks = _drinkRepository.Drinks
                       .Where(p => p.Category.CategoryName == "Non-alcoholic").OrderBy(p => p.Name);
                }
                currentCategory = category;

            }
            var model = new DrinksViewModel()
            {
                Drinks = drinks,
                CurrentCategory = currentCategory
            };
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Detail(int drinkId)
        {
            var drink = _drinkRepository.Drinks.FirstOrDefault(d => d.DrinkId == drinkId);
            if (drink == null)
            {
                ViewBag.ErrorMessage = $"the drink has id : {drinkId} not found";
                return View("Error");
            }
            ViewBag.drinkId = drinkId;
            var model = new DetailViewModel()
            {
                Name = drink.Name,
                LongDescription = drink.LongDescription,
                ImageUrl = drink.ImageUrl
            };
            return View(model);
        }
      
        public IActionResult ManagerDrinks()
        {
            IEnumerable<Drink> drinks;
            drinks = _drinkRepository.Drinks.OrderBy(d => d.DrinkId);

            var model = new DrinksViewModel()
            {
                Drinks = drinks,
                CurrentCategory = "All Drink"
            };
            return View(model);
        }
        [HttpGet]
        
        public IActionResult Delete(int drinkId)
        {
            _drinkRepository.Delete(drinkId);
            return RedirectToAction("ManagerDrinks");
        }
       
        public IActionResult Create()
        {
            return View();
        }
        private List<string> ProcessUploadedFile(CreateDrinkViewModel model1, CreateDrinkViewModel model2)
        {
            string uniqueFileName1 = null;
            string uniqueFileName2 = null;
          
            if (model1.ImageUrl != null)
            {
                string uploadFile = Path.Combine(webHostEnvironment.WebRootPath, "ImageUrl");
                uniqueFileName1 = Guid.NewGuid().ToString() + model1.ImageUrl.FileName;
                string filePath1 = Path.Combine(uploadFile, uniqueFileName1);
                using (var fileStream1 = new FileStream(filePath1, FileMode.Create))
                model1.ImageUrl.CopyTo(fileStream1);     
            }
            if (model2.ImageThumbnailUrl != null)
            {
                string uploadFile = Path.Combine(webHostEnvironment.WebRootPath, "ImageThumbnailUrl");
                uniqueFileName2 = Guid.NewGuid().ToString() + model2.ImageThumbnailUrl.FileName;
                string filePath2 = Path.Combine(uploadFile, uniqueFileName2);
                using (var fileStream2 = new FileStream(filePath2, FileMode.Create))
                model2.ImageThumbnailUrl.CopyTo(fileStream2);
            }
            List<string> uniqueFileName = new List<string>()
            {
                uniqueFileName1,
                uniqueFileName2
            };
            return uniqueFileName;
        }
        [HttpPost]
        public IActionResult Create(CreateDrinkViewModel model)
        {
            if (ModelState.IsValid)
            {
                List<string> uniqueFileName = ProcessUploadedFile(model, model);
                string uniqueFileName1 = uniqueFileName[0];
                string uniqueFileName2 = uniqueFileName[1];
                Drink drink = new Drink()
                {
                    Name = model.Name,
                    ShortDescription = model.ShortDescription,
                    LongDescription = model.LongDescription,
                    Price = model.Price,
                    ImageUrl = uniqueFileName1,
                    ImageThumbnailUrl = uniqueFileName2,
                    IsPreferredDrink = model.IsPreferredDrink,
                    InStock = model.InStock,
                    CategoryId = model.CategoryId
                };
                _drinkRepository.Add(drink);
                return RedirectToAction("ManagerDrinks");
            }
            return View(model);
        }

    }
}

Views/Shared/Carousel.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-slide-to="0" class="active"></li>
        <li data-slide-to="1"></li>
        <li  data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel3.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

Views/Shared/ConfirmEmail.cshtml
@{
    ViewData["Title"] = "ConfirmEmail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Confirm Email</h1>
<div class="btn btn-primary ">
    Before you can login, Please confirm your email by click on the confirmation link we haved email you
</div>

Views/Shared/DrinksSummary.cshtml
@model Drink

<div class="col-sm-4 col-lg-4 col-md-4 mt-2" style="float:left;">
    <div class="img-thumbnail product">
        <img src="~/ImageThumbnailUrl/@Model.ImageThumbnailUrl" alt="Alternate Text" asp-append-version="true" width="320" height="200"/>
        <div class="caption">
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
            <h3>
                <a asp-action="detail" asp-controller="drink" asp-route-drinkId="@Model.DrinkId">@Model.Name</a>
            </h3>
            <p>@Model.ShortDescription</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-success " id="cartButton" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-drinkId="@Model.DrinkId">
                    Add to cart
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/ForgotPasswordConfirmation.cshtml
@{
    ViewData["Title"] = "Forgot Password Confirmation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Forgot Password Confirmation</h1>
<div class="btn btn-primary">
    Before you can reset your password, Please confirm your email by click on the confirmation link we haved email you
</div>

Views/Shared/Successfully.cshtml
@{
    ViewData["Title"] = "Successfully";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Successfully</h1>

<div class="btn btn-primary ">
    Your email has been verified ! You can click the button to go to Login
</div>
<button class="btn btn-primary" asp-action="login" asp-controller="Account">Login</button>

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    @*validate client side*@
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    @*css*@
    @RenderSection("Header",required:false)
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark menu">
            <a class="navbar-brand logo" href="#"><img src="~/images/unnamed.jpg" alt="" width="200" height="95"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {

                        <li class="nav-item dropdown products">
                            <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" style="color:black" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                UTILITIES
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-action="listOrders" asp-controller="order">Order</a>
                                <a class="dropdown-item" asp-action="ManagerDrinks" asp-controller="drink">Products</a>
                                <a class="dropdown-item" asp-action="index" asp-controller="home">Home</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item link">
                            <a class="nav-link" asp-action="index" asp-controller="home">HOME</a>
                        </li>
                    }
                    <li class="nav-item dropdown drinks">
                        <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" style="color:black" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            DRINKS
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-action="list" asp-controller="drink">All</a>
                            <a class="dropdown-item" asp-action="list" asp-controller="drink" asp-route-category="Alcoholic">Alcoholic</a>
                            <a class="dropdown-item" asp-action="list" asp-controller="drink" asp-route-category="Non-alcoholic">Non-alcoholic</a>
                        </div>
                    </li>
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                    {
                        <li class="nav-item dropdown manager">
                            <a class="nav-link dropdown-toggle " id="navbarDropdown" role="button" style="color:black" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                MANAGER
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-action="ListRoles" asp-controller="administration">Role</a>
                                <a class="dropdown-item" asp-action="ListUsers" asp-controller="administration">Users</a>
                            </div>
                        </li>
                    }
                    else
                    {
                        <div class="noManager"></div>
                    }
                    <li class="nav-item">
                        <form class="form-inline my-2 my-lg-0" asp-controller="Drink" asp-action="Search" method="get">
                            <input class="form-control mr-sm-2" placeholder="Search" value="@ViewData["searchString"]">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                    </li>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item link lg">
                            <a class="nav-link" asp-action="logout" asp-controller="account">
                                Logout <span>@User.Identity.Name</span>
                            </a>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item link lg">
                            <a class="nav-link" asp-action="register" asp-controller="account">REGISTER</a>
                        </li>
                        <li class="nav-item link lg">
                            <a class="nav-link" asp-action="login" asp-controller="account">LOGIN</a>
                        </li>
                    }

                </ul>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

</body>

</html>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@RenderSection("Scripts", required: false)